[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
optimizer_runs = 100_000
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.ci]
fuzz = { runs = 25000 }

[fmt]
line_length = 80
multiline_func_header = 'params_first'
